### ISSUE TITLE
No module named web

### ISSUE THREAD

**Issue by vor7ex** [dineshshetty/Android-InsecureBankv2#29]
I run this command:
$python app.py

Error:
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import web
ImportError: No module named web

If i run this command:
$python2 -m pip install web.py==0.51

Error:
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by vor7ex** [comment]
$sudo apt install python-setuptools
$python2 -m pip install web.py==0.51

and solved.

**Comment by nocomp** [comment]
hi folks,

trying to run it on kali, suffering...
┌──(nocomp㉿R3dB0x)-[~/tools/android/Android-InsecureBankv2/AndroLabServer]
└─$ pip install web.py==0.51                                                                            1 ⨯
Defaulting to user installation because normal site-packages is not writeable
Collecting web.py==0.51
  Downloading web.py-0.51.tar.gz (80 kB)
     |████████████████████████████████| 80 kB 2.7 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-s70wejm6/web-py_493179d08eec4dac81e99cd2491922e9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-s70wejm6/web-py_493179d08eec4dac81e99cd2491922e9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-t4unuew4                                                                    
         cwd: /tmp/pip-install-s70wejm6/web-py_493179d08eec4dac81e99cd2491922e9/                            
    Complete output (36 lines):                                                                             
    running egg_info                                                                                        
    creating /tmp/pip-pip-egg-info-t4unuew4/web.py.egg-info                                                 
    writing /tmp/pip-pip-egg-info-t4unuew4/web.py.egg-info/PKG-INFO                                         
    writing dependency_links to /tmp/pip-pip-egg-info-t4unuew4/web.py.egg-info/dependency_links.txt         
    writing requirements to /tmp/pip-pip-egg-info-t4unuew4/web.py.egg-info/requires.txt                     
    writing top-level names to /tmp/pip-pip-egg-info-t4unuew4/web.py.egg-info/top_level.txt                 
    writing manifest file '/tmp/pip-pip-egg-info-t4unuew4/web.py.egg-info/SOURCES.txt'                      
    Traceback (most recent call last):                                                                      
      File "<string>", line 1, in <module>                                                                  
      File "/tmp/pip-install-s70wejm6/web-py_493179d08eec4dac81e99cd2491922e9/setup.py", line 15, in <module>                                                                                                           
        setup(                                                                                              
      File "/home/nocomp/.local/lib/python3.9/site-packages/setuptools/__init__.py", line 145, in setup     
        return distutils.core.setup(**attrs)                                                                
      File "/usr/lib/python3.9/distutils/core.py", line 148, in setup                                       
        dist.run_commands()                                                                                 
      File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands                                
        self.run_command(cmd)                                                                               
      File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command                                 
        cmd_obj.run()                                                                                       
      File "/home/nocomp/.local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 296, in run                                                                                                           
        self.find_sources()                                                                                 
      File "/home/nocomp/.local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 303, in find_sources                                                                                                  
        mm.run()                                                                                            
      File "/home/nocomp/.local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 534, in run                                                                                                           
        self.add_defaults()                                                                                 
      File "/home/nocomp/.local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 574, in add_defaults                                                                                                  
        rcfiles = list(walk_revctrl())                                                                      
      File "/home/nocomp/.local/lib/python3.9/site-packages/setuptools/command/sdist.py", line 20, in walk_revctrl                                                                                                      
        for item in ep.load()(dirname):                                                                     
      File "/home/nocomp/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2442, in load  
        self.require(*args, **kwargs)                                                                       
      File "/home/nocomp/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2465, in require                                                                                                           
        items = working_set.resolve(reqs, env, installer, extras=self.extras)                               
      File "/home/nocomp/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 791, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)                                        
    pkg_resources.VersionConflict: (setuptools 41.6.0 (/home/nocomp/.local/lib/python3.9/site-packages), Requirement.parse('setuptools>=45'))                                                                           
    ----------------------------------------                                                                
WARNING: Discarding https://files.pythonhosted.org/packages/45/81/4f598ed7089a7be632d5787882c8a384f413ef4262b4fe30b1972e61f9dc/web.py-0.51.tar.gz#sha256=b50343941360984d37270186453bb897d13630028a739394fedf38f9cde2fd07 (from https://pypi.org/simple/web-py/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.                                                                      
ERROR: Could not find a version that satisfies the requirement web.py==0.51 (from versions: 0.22, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.40.dev0, 0.40.dev1, 0.40, 0.51, 0.60, 0.61, 0.62)                         
ERROR: No matching distribution found for web.py==0.51
                                                                                                            
┌──(nocomp㉿R3dB0x)-[~/tools/android/Android-InsecureBankv2/AndroLabServer]
└─$                                                                                                     1 ⨯
any options?
*thxx for your help
